### ISSUE TITLE
CODE CAN NOT RUN

### ISSUE THREAD

**Issue by GuangZhaoZhou** [AbangLZU/ndt_localizer#2]
this code is dependent on the topic "init_pose",where can I get?
我真是服了，白白浪费时间。

**Comment by AbangLZU** [comment]
@GuangZhaoZhou 
Set the init pose with Rviz 2D Pose Estimate  button, which has already discussed in the README.md. Please read the README.md carefully!!
请仔细阅读README.md 以掌握如何使用，谢谢！
If you want more detail (step by step tutorial and understanding of the algorithm), please read my blog here: https://adamshan.blog.csdn.net/article/details/106739856
如果你需要了解算法详情，以及一步一步教你如何使用本项目，请参考该博客：https://adamshan.blog.csdn.net/article/details/106739856
