### ISSUE TITLE
Sample pcd map and sample bag file to run the module

### ISSUE THREAD

**Issue by chowkamlee81** [AbangLZU/ndt_localizer#4]
Can you please share the Sample pcd map and sample bag file to run the module

**Comment by AbangLZU** [comment]
You can reproduce my blog https://blog.csdn.net/AdamShan/article/details/106739856?spm=1001.2014.3001.5501 and https://blog.csdn.net/AdamShan/article/details/106589633?spm=1001.2014.3001.5501 to use Mulran dataset to build your pcd map and produce the pointcloud data. Unfortunately, the blog is written with Chinese, if you can not read Chinese blog and want to reproduce the project demo, use the link below(Baidu disk) to download the pcd map and rosbag:

link: https://pan.baidu.com/s/1hZ0VuQCy4KX3lHUTFdVeww  passward: r7fl


> The KAIST02-small.bag is not the whole KAIST02 dataset, because the rosbag do not compress data, the whole KAIST02 rosbag is too large. So I use the first 81 seconds of the KAIST02 dataset to make this small rosbag.
