### ISSUE TITLE
bug提交

### ISSUE THREAD

**Issue by DashBear** [AbangLZU/ndt_localizer#6]
体素滤波的这个if(measurement_range != MAX_MEASUREMENT_RANGE)语句是个bug,这个语句按照现在程序写的,最前面宏定义再赋值,不可能满足不等这个条件，会导致裁剪点云的语句失效

**Comment by AbangLZU** [comment]
Thanks for your feedback. Already fix it in the new commit:
02612c5ea5998fd96aee8d3b4da9c34dc22943f2
